### ISSUE TITLE
Does it support SSR with Nuxt.js? 

### ISSUE THREAD

**Issue by bovas85** [e2o/vue-element-query#3]
I know this is likely using window and document.

Is the lib checking if window is defined?

**Comment by e2o** [comment]
This plugin does indeed use event listeners for resize on `window`.

Try importing this plugin on the client-side. Did you [check out this entry in the nuxt docs](https://nuxtjs.org/faq/window-document-undefined/)?

Let me know if it worked :)

**Comment by bovas85** [comment]
Yes I'm aware of that, Nuxt uses a plugin system where you can specify ssr: false.
The issue here is that it breaks if the plugin is not supporting ssr in a way that checks for window object to exist first or all. 

The other ways to import it client side only are hacks rather than native and it usually boils down to just checking the window is defined :) 

I'm on my mobile now but I'll check later today or tomorrow

**Comment by bondzula** [comment]
I used it without `ssr: false` didn't see any issues

**Comment by bovas85** [comment]
Fantastic that's all good then
