### ISSUE TITLE
Is it possible to use data or props attribute for definition of breakpoints?

### ISSUE THREAD

**Issue by robertfausk** [e2o/vue-element-query#7]
The following actually fails cause of ```this``` is not defined:
```JS
    export default {
        props: {
            breakPointWidth: {
                type: Number,
                required: true,
            },
        },
        eq: {
            breakpoints: {
                large: {minWidth: this.breakPointWidth},
            },
        },
    }
```

Can you give me a hint how to solve this?

**Comment by e2o** [comment]
Hello @robertfausk, currently the library does not support this, as the `eq`-property would have to be inside a `data()`-function for that. 

I am currently not intending on further developing this library, so no plans on adding support for this.
